### ISSUE TITLE
SteamKit 1.6.4 updates

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/SteamDatabase#366]
- [x] New server management - SteamRE/SteamKit#135
- [x] New callback API - SteamRE/SteamKit#124
- [x] Implemented free license handler - SteamRE/SteamKit#142
- [x] Binary KV changes (affects package info) - SteamRE/SteamKit#138
